on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-pages]
  push:
    branches:
      - master
    paths:
      - 'public/**'
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
